[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000
solc_version = "0.8.20"

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"




